class Locators():

    postcode_loc_id = "postcode"
    get_a_quote_loc_id = "get-storage-price-v-35"
    close_popup_loc_nxt1 = "step1"
    close_popup_loc_id = "skip"
    sq_ft_loc_size = "//body[1]/main[1]/div[1]/div[3]/div[2]/div[1]/ul[1]/div[1]/div[1]/div[1]/div[2]/div[1]/li[1]"
    cont1_click_loc_wizard = "v-35-step1-cta-next"
    step_2_postcode_loc_box = "postcode"
    step_2_pc_address_line1_loc = "//body[1]/main[1]/div[1]/div[3]/div[1]/form[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]"
    step_2_pc_address_line2_loc = "//body[1]/main[1]/div[1]/div[3]/div[1]/form[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]"
    month_drop_lc = "selectedInquiryDiv"
    month_drop_val_lc = "//li[@id='48']"
    pick_up_date_lc = "opener"
    date_select_lc = "//a[contains(text(),'11')]"
    time_select_lc = "//body/main[1]/div[1]/div[3]/div[1]/form[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/ul[1]/li[3]/label[1]"
    save_time_date_lc ="tslotSaveBtn"
    packing_assistance_lc = "packingAssistance"
    discount_code_lc = "coupon-code"
    cont2_click_lc = "v-35-step2-cta-next"
    name_lc = "name"
    email_lc = "email"
    phone_lc = "customerPhone"
    step_3_btn = "v-35-step3-cta-next"
    profile_lc = "//body/div[4]/ul[1]/li[4]"
    logout_lc = "//span[contains(text(),'Logout')]"
    loginemail_lc = "email"
    loginpass_lc = "password"
    logintbn_lc = "btnLoginSubmit"